version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3316:3306'
    volumes:
      - ./db:/var/lib/mysql

  web:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/Longinus
    depends_on:
      - db
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
