version: '3'

services:
  db:
    image: postgres:10.5
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  web:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/Longinus
    depends_on:
      - db
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
