version: '3'
services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./web:/Longinus
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
  db:
    build: ./db
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf:/etc/mysql/conf.d
    expose:
      - "3306"
