@startuml

class User {
  id  : int
  name : string
  email  : string
  password_digest : string
}
class UserIntroduction {
  id : int
  user_id : int
  category_id : int
  element_id : int
}
class Category {
  id : int
  name : string
}

class Element {
  id : int
  category_id : int
  name : int
}

UserIntroduction  <--  User 
UserIntroduction  <--  Element
UserIntroduction  <--  Category
Element  <-r-  Category

@enduml
